Fix eslint error:
node_modules/eslint/lib/rules/no-unused-vars.js:121
                if (type === "Parameter" && def.node.parent.type === "Property
                                                           ^
TypeError: Cannot read property 'type' of undefined
    at getUnusedLocals (node_modules/eslint/lib/rules/no-unused-vars.js:121:60)
    at Array.map (native)
    at getUnusedLocals (node_modules/eslint/lib/rules/no-unused-vars.js:141:58)
    at Array.map (native)
    at getUnusedLocals (node_modules/eslint/lib/rules/no-unused-vars.js:141:58)
    at Array.map (native)
    at getUnusedLocals (node_modules/eslint/lib/rules/no-unused-vars.js:141:58)
    at Array.map (native)
    at getUnusedLocals (node_modules/eslint/lib/rules/no-unused-vars.js:141:58)
    at EventEmitter.Program:exit (node_modules/eslint/lib/rules/no-unused-vars.js:147:26)